### ISSUE TITLE
scons not working on win10

### ISSUE THREAD

**Issue by yankscally** [YuriSizov/gdsion#2]
tried to scons and build this but it didn't work.

excited to try this out!

**Comment by yankscally** [comment]
```
scons: Reading SConscript files ...
scons: *** missing SConscript file 'godot-cpp\\SConstruct
File "C:\Users\micro\Downloads\gdsion-main\SConstruct", line 4, in <module>```

**Comment by YuriSizov** [comment]
Hey there! This project uses git submodules, so you need to check it out via git, the downloaded ZIP would be incomplete.

Alternatively you can also download godot-cpp manually and put it into the godot-cpp folder. But I would recommend using git to make sure it's the exact tested version.

I should mention submodules clearly in the readme instructions. Thanks for pointing this out!
