### ISSUE TITLE
Playing certain MML sample songs makes the visualizer disappear forever

### ISSUE THREAD

**Issue by YuriSizov** [YuriSizov/gdsion#23]
Noticed with `Twin Memories / Pop'nツインビー (Stage1)`. Playing it in the example app makes the visualizer go away and never to reappear even with other songs. This particular song is also panned completely to the right, which may be a part of the problem. I haven't looked into whether it should be like that.

**Comment by djtuBIG-MaliceX** [comment]
Pretty cool you've got the mmltalks salvage tracks at least 'running' in your port. Seriously great work.  (lowkey been hoping a C++ port of SiON would eventually exist).

I've still kept a copy of the old .swf editors for playing the original tracks back in the original engine if you need a reference recording.

**Comment by djtuBIG-MaliceX** [comment]
Recording with the last sion065.swc mmleditor.air program version :  https://www.youtube.com/watch?v=QiCyH_OPlCs

**Comment by YuriSizov** [comment]
> Pretty cool you've got the mmltalks salvage tracks at least 'running' in your port.

Thank you! I think pretty much all of them sound exactly as they should too, and there is one that would crash SiON due to some strange syntax inserts, but works fine with GDSiON, so we're even improving here :)

> lowkey been hoping a C++ port of SiON would eventually exist

I'm curious if anyone would want a pure C/C++ library for this. Right now it's tightly coupled with Godot's extension API, so it cannot be used standalone. But it is of course possible to rewrite bits and parts of it and split the underlying synth from the Godot bindings that I use for Bosca and Glasan.

> I've still kept a copy of the old .swf editors for playing the original tracks back in the original engine if you need a reference recording.

Thanks, that's very helpful! I typically use my local setup with Bosca Ceoil to test things with SiON. Just didn't get to investigating this particular bug. But your recordings seems to confirm that it is indeed a bug, so I'll look into it today.
